server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ocpproducts_db
    username: postgres
    password: ikram
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 590034236419-ofusekhu4ii8o04omg7nun925fao1u8o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
